# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/system.xdc

# IP: ip/rgb2dvi_0/rgb2dvi_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rgb2dvi_0 || ORIG_REF_NAME==rgb2dvi_0} -quiet] -quiet

# IP: ip/Clk_Division_0/Clk_Division_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Clk_Division_0 || ORIG_REF_NAME==Clk_Division_0} -quiet] -quiet
